from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from pii_prep.format_filter import FormatFilter


ZERO_EXAMPLE_LABELS = [
    "BANK_ACCOUNT_INFORMATION",
    "FIRST_NAME",
    "HOME_PHONE",
    "LAST_NAME",
]

CONTEXT_TYPES = [
    "bare_span",
    "weak_context",
    "strong_positive_context",
    "reverse_negative_context",
]

VERDICTS = [
    "strong_for",
    "weak_for",
    "neutral",
    "weak_against",
    "strong_against",
]

AMBIGUITY_GROUPS = [
    {
        "name": "numeric_id",
        "span": "123456789",
        "candidates": ["BANK_ACCOUNT_NUMBER", "STUDENT_ID", "EMPLOYEE_NUMBER", "AU_TFN", "NON_PII"],
        "contexts": {
            "bare_span": "123456789",
            "weak_context": "Reference: 123456789",
            "strong_positive_context": "Student ID 123456789 was used for enrolment.",
            "reverse_negative_context": "Order #123456789 shipped from the warehouse.",
        },
    },
    {
        "name": "phone_number",
        "span": "(02) 4567 8901",
        "candidates": ["MOBILE", "HOME_PHONE", "WORK_PHONE", "NON_PII"],
        "contexts": {
            "bare_span": "(02) 4567 8901",
            "weak_context": "Contact: (02) 4567 8901",
            "strong_positive_context": "Home phone (02) 4567 8901 is the preferred after-hours contact.",
            "reverse_negative_context": "Support ticket (02) 4567 8901 was generated by the test suite.",
        },
    },
    {
        "name": "date",
        "span": "04/05/1998",
        "candidates": ["DATE_OF_BIRTH", "PASSPORT_EXPIRY", "PASSPORT_START_DATE", "MEDICARE_EXPIRY", "NON_PII"],
        "contexts": {
            "bare_span": "04/05/1998",
            "weak_context": "Date: 04/05/1998",
            "strong_positive_context": "Date of birth 04/05/1998 was confirmed during intake.",
            "reverse_negative_context": "Meeting room 04/05/1998 was listed in an old migration log.",
        },
    },
    {
        "name": "email",
        "span": "alex.chen@example.com",
        "candidates": ["EMAIL_ADDRESS", "WORK_EMAIL", "NON_PII"],
        "contexts": {
            "bare_span": "alex.chen@example.com",
            "weak_context": "Address: alex.chen@example.com",
            "strong_positive_context": "Please email Alex at alex.chen@example.com about the case.",
            "reverse_negative_context": "The documentation uses alex.chen@example.com as a placeholder address.",
        },
    },
    {
        "name": "name",
        "span": "Mia",
        "candidates": ["PERSON", "FIRST_NAME", "LAST_NAME", "NON_PII"],
        "contexts": {
            "bare_span": "Mia",
            "weak_context": "Name: Mia",
            "strong_positive_context": "First name: Mia",
            "reverse_negative_context": "The code Mia is used as an acronym in the internal status report.",
        },
    },
    {
        "name": "address",
        "span": "12 King St",
        "candidates": ["ADDRESS", "GEOLOCATION_INFORMATION", "NON_PII"],
        "contexts": {
            "bare_span": "12 King St",
            "weak_context": "Location: 12 King St",
            "strong_positive_context": "Residential address 12 King St was confirmed on the form.",
            "reverse_negative_context": "The sample map labels 12 King St as a fictional example.",
        },
    },
    {
        "name": "coordinates",
        "span": "-33.8688",
        "candidates": ["LATITUDE", "LONGITUDE", "GEOLOCATION_INFORMATION", "NON_PII"],
        "contexts": {
            "bare_span": "-33.8688",
            "weak_context": "Coordinate: -33.8688",
            "strong_positive_context": "Latitude -33.8688 was captured for the residential address.",
            "reverse_negative_context": "Version -33.8688 appears in the simulated telemetry output.",
        },
    },
    {
        "name": "vehicle",
        "span": "ABC123",
        "candidates": ["NUMBER_PLATE", "VEHICLE_REGO", "USERNAME", "NON_PII"],
        "contexts": {
            "bare_span": "ABC123",
            "weak_context": "Identifier: ABC123",
            "strong_positive_context": "Vehicle rego ABC123 is attached to the parking permit.",
            "reverse_negative_context": "Build code ABC123 completed successfully overnight.",
        },
    },
    {
        "name": "card_or_health_id",
        "span": "4111111111111111",
        "candidates": ["PAYMENT_CARD_NUMBER", "MEDICARE_NUMBER", "IHI", "NON_PII"],
        "contexts": {
            "bare_span": "4111111111111111",
            "weak_context": "Number: 4111111111111111",
            "strong_positive_context": "Payment card number 4111111111111111 was entered on the billing page.",
            "reverse_negative_context": "Test token 4111111111111111 was generated by the sandbox.",
        },
    },
    {
        "name": "social_account",
        "span": "alex_chen91",
        "candidates": ["SOCIAL_MEDIA_ACCOUNT", "SOCIAL_MEDIA_ID", "USERNAME", "NON_PII"],
        "contexts": {
            "bare_span": "alex_chen91",
            "weak_context": "Handle: alex_chen91",
            "strong_positive_context": "Social media account alex_chen91 was listed on the disclosure form.",
            "reverse_negative_context": "The tutorial uses alex_chen91 as a fake login example.",
        },
    },
]


def generate_stage2_artifacts(
    root: Path | str = ".",
    zero_examples_per_label: int = 20,
    prompt_sample_size: int = 20,
    enforce_expected_counts: bool = True,
) -> dict[str, Any]:
    root = Path(root)
    canonical_labels = _read_json(root / "pii_schema" / "canonical_labels_79.json")
    training_labels = _read_json(root / "pii_schema" / "training_label_space_80.json")
    training_label_set = set(training_labels)
    if enforce_expected_counts and len(canonical_labels) != 79:
        raise ValueError(f"canonical label count must be 79, got {len(canonical_labels)}")
    if enforce_expected_counts and (len(training_labels) != 80 or "NON_PII" not in training_label_set):
        raise ValueError("training label space must be 79 canonical labels plus NON_PII")

    seed_records: list[dict[str, Any]] = []
    seed_records.extend(generate_zero_example_records(training_label_set, zero_examples_per_label))
    seed_records.extend(generate_candidate_level_negatives(training_label_set))
    seed_records.extend(generate_document_level_negatives())
    seed_errors = validate_seed_records(seed_records, training_label_set)
    if seed_errors:
        raise ValueError("stage2 seed validation failed: " + "; ".join(seed_errors[:5]))

    prompts = generate_teacher_prompt_samples(training_label_set, prompt_sample_size)
    prompt_errors = validate_prompt_records(prompts, training_label_set)
    if prompt_errors:
        raise ValueError("stage2 prompt validation failed: " + "; ".join(prompt_errors[:5]))

    generated_dir = root / "data" / "generated"
    reports_dir = root / "reports"
    generated_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    _write_jsonl(generated_dir / "stage2_seed_examples.jsonl", seed_records)
    _write_jsonl(generated_dir / "stage2_teacher_prompts_sample.jsonl", prompts)

    zero_counts = {
        label: sum(
            1
            for record in seed_records
            for span in record["spans"]
            if record["metadata"].get("source") == "synthetic_zero_example" and span["top_type"] == label
        )
        for label in ZERO_EXAMPLE_LABELS
    }
    zero_plan = {
        "zero_example_labels": ZERO_EXAMPLE_LABELS,
        "examples_per_label": zero_examples_per_label,
        "generated_counts": zero_counts,
        "generation_mode": "local_draft_examples_no_teacher_calls",
    }
    generation_plan = {
        "stage": "2",
        "teacher_model_path": "/home/admin/model/qwen3.5-27b",
        "teacher_calls_executed": 0,
        "teacher_prompt_sample_count": len(prompts),
        "seed_record_count": len(seed_records),
        "zero_example_record_count": sum(zero_counts.values()),
        "candidate_level_negative_count": sum(1 for r in seed_records if r["metadata"].get("subtype") == "candidate_level"),
        "document_level_negative_count": sum(1 for r in seed_records if r["metadata"].get("subtype") == "doc_level"),
        "context_types": CONTEXT_TYPES,
        "verdicts": VERDICTS,
        "next_gate": "inspect 20 teacher prompts before running batch teacher calls",
    }
    _write_json(reports_dir / "zero_example_label_plan.json", zero_plan)
    _write_json(reports_dir / "stage2_generation_plan.json", generation_plan)
    return generation_plan


def generate_zero_example_records(training_labels: set[str], examples_per_label: int) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for label in ZERO_EXAMPLE_LABELS:
        if label not in training_labels:
            raise ValueError(f"zero-example label not in training space: {label}")
        for index in range(examples_per_label):
            text, value = zero_example_text(label, index)
            records.append(
                make_span_record(
                    record_id=f"STAGE2-ZERO-{label}-{index + 1:03d}",
                    text=text,
                    value=value,
                    label=label,
                    metadata={
                        "source": "synthetic_zero_example",
                        "data_category": "stage2_zero_example_positive",
                        "target_label": label,
                    },
                    distribution={label: 0.95, "NON_PII": 0.05},
                    format_candidates=[label, "NON_PII"],
                    training_weight=0.6,
                )
            )
    return records


def zero_example_text(label: str, index: int) -> tuple[str, str]:
    first_names = [
        "Amelia",
        "Noah",
        "Olivia",
        "Liam",
        "Ava",
        "Jack",
        "Mia",
        "Henry",
        "Grace",
        "Leo",
        "Sophie",
        "Ethan",
        "Ruby",
        "Lucas",
        "Zoe",
        "Archer",
        "Chloe",
        "Mason",
        "Ella",
        "Hugo",
    ]
    last_names = [
        "Nguyen",
        "Smith",
        "Patel",
        "Chen",
        "Singh",
        "Williams",
        "Brown",
        "Taylor",
        "Wilson",
        "Martin",
        "Anderson",
        "Thompson",
        "Walker",
        "White",
        "Harris",
        "Lee",
        "Clark",
        "Lewis",
        "Young",
        "King",
    ]
    home_phones = [f"(02) 45{index:02d} {8900 + index:04d}" for index in range(20)]
    bank_phrases = [
        "banking details",
        "bank account information",
        "payroll banking information",
        "direct debit banking details",
        "refund account information",
        "deposit account details",
        "payment account information",
        "bank transfer details",
        "account holder banking details",
        "student refund banking information",
        "supplier banking details",
        "grant payment account information",
        "nominated banking details",
        "financial account information",
        "banking profile details",
        "account payment instructions",
        "bank account verification details",
        "settlement account information",
        "reimbursement banking details",
        "fee refund account information",
    ]
    i = index % 20
    if label == "FIRST_NAME":
        value = first_names[i]
        return f"First name: {value} was confirmed during enrolment.", value
    if label == "LAST_NAME":
        value = last_names[i]
        return f"Last name: {value} appears on the signed application.", value
    if label == "HOME_PHONE":
        value = home_phones[i]
        return f"Home phone {value} is the preferred after-hours contact number.", value
    if label == "BANK_ACCOUNT_INFORMATION":
        value = bank_phrases[i]
        return f"The form includes {value} for refund processing.", value
    raise ValueError(f"unsupported zero-example label: {label}")


def generate_candidate_level_negatives(training_labels: set[str]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for index, group in enumerate(AMBIGUITY_GROUPS, 1):
        candidates = filter_candidates(group["candidates"], training_labels)
        if len(candidates) <= 1:
            continue
        context = group["contexts"]["reverse_negative_context"]
        span_value = group["span"]
        pii_candidates = [candidate for candidate in candidates if candidate != "NON_PII"]
        dist = {"NON_PII": 0.75}
        share = round(0.25 / min(3, len(pii_candidates)), 6) if pii_candidates else 0.0
        for candidate in pii_candidates[:3]:
            dist[candidate] = share
        total = sum(dist.values())
        dist["NON_PII"] = round(dist["NON_PII"] + (1.0 - total), 6)
        records.append(
            make_span_record(
                record_id=f"STAGE2-CAND-NEG-{index:03d}",
                text=context,
                value=span_value,
                label="NON_PII",
                metadata={
                    "source": "synthetic_ambiguous_negative",
                    "data_category": "stage2_candidate_level_negative",
                    "subtype": "candidate_level",
                    "ambiguity_group": group["name"],
                },
                distribution=dist,
                format_candidates=candidates,
                training_weight=0.5,
            )
        )
    return records


def generate_document_level_negatives() -> list[dict[str, Any]]:
    texts = [
        "Order #123456 shipped today from the warehouse staging system.",
        "The sandbox generated ticket ABC123 for documentation testing.",
        "Reference 04/05/1998 appears in the migration guide as a format example.",
        "Placeholder alex.chen@example.com is used in this public help article.",
    ]
    return [
        {
            "id": f"STAGE2-DOC-NEG-{index:03d}",
            "text": text,
            "metadata": {
                "source": "synthetic_document_negative",
                "data_category": "stage2_document_level_negative",
                "subtype": "doc_level",
            },
            "spans": [],
        }
        for index, text in enumerate(texts, 1)
    ]


def generate_teacher_prompt_samples(training_labels: set[str], prompt_sample_size: int) -> list[dict[str, Any]]:
    prompts: list[dict[str, Any]] = []
    for group in AMBIGUITY_GROUPS:
        candidates = filter_candidates(group["candidates"], training_labels)
        if len(candidates) <= 1:
            continue
        for context_type in CONTEXT_TYPES:
            context = group["contexts"][context_type]
            prompt_id = f"STAGE2-PROMPT-{len(prompts) + 1:03d}"
            prompts.append(
                {
                    "id": prompt_id,
                    "ambiguity_group": group["name"],
                    "context_type": context_type,
                    "span_value": group["span"],
                    "context": context,
                    "candidate_labels": candidates,
                    "prompt": build_5way_prompt(group["span"], context, candidates),
                    "teacher_model_path": "/home/admin/model/qwen3.5-27b",
                    "teacher_call_status": "not_run",
                }
            )
            if len(prompts) >= prompt_sample_size:
                return prompts
    return prompts


def build_5way_prompt(span_value: str, context: str, candidates: list[str]) -> str:
    candidate_lines = "\n".join(f"- {candidate}" for candidate in candidates)
    return (
        "You will assess the likelihood that a given text span belongs to each candidate\n"
        "PII type, given the context.\n\n"
        f'Span: "{span_value}"\n'
        f'Context: "{context}"\n\n'
        "This span passes format checks for these candidate types:\n"
        f"{candidate_lines}\n\n"
        "For each candidate, assign EXACTLY ONE of these 5 verdicts:\n"
        '- "strong_for"      : Context strongly suggests this type\n'
        '- "weak_for"        : Context mildly suggests this type\n'
        '- "neutral"         : No evidence either way\n'
        '- "weak_against"    : Context mildly contradicts this type\n'
        '- "strong_against"  : Context strongly contradicts this type\n\n'
        "Also assess NON_PII (the span being not a PII at all).\n\n"
        "Context-specific rules:\n"
        "- bare_span: Do not use strong_for unless the format uniquely identifies one label.\n"
        "- bare_span: Date-like bare spans must remain ambiguous across date-related labels and NON_PII.\n"
        "- weak_context: Avoid strong_for unless the field name explicitly identifies the label.\n"
        "- strong_positive_context: strong_for is allowed when the context clearly identifies the label.\n"
        "- reverse_negative_context: NON_PII should usually be strong_for.\n"
        "- reverse_negative_context: PII labels that only match by format should usually be weak_against or strong_against.\n\n"
        "Output JSON only:\n"
        "{\n"
        '  "verdicts": {\n'
        '    "CANDIDATE_LABEL": "neutral",\n'
        '    "NON_PII": "neutral"\n'
        "  }\n"
        "}"
    )


def filter_candidates(candidates: list[str], training_labels: set[str]) -> list[str]:
    filtered = []
    for candidate in candidates:
        if candidate in training_labels and candidate not in filtered:
            filtered.append(candidate)
    if "NON_PII" in training_labels and "NON_PII" not in filtered:
        filtered.append("NON_PII")
    return filtered


def format_compatible_candidates(span_value: str, candidates: list[str], training_labels: set[str]) -> list[str]:
    allowed = FormatFilter.get_candidates(span_value)
    compatible = [candidate for candidate in candidates if candidate in allowed]
    return filter_candidates(compatible, training_labels)


def make_span_record(
    record_id: str,
    text: str,
    value: str,
    label: str,
    metadata: dict[str, Any],
    distribution: dict[str, float],
    format_candidates: list[str],
    training_weight: float,
) -> dict[str, Any]:
    start = text.index(value)
    end = start + len(value)
    return {
        "id": record_id,
        "text": text,
        "metadata": metadata,
        "spans": [
            {
                "start": start,
                "end": end,
                "value": value,
                "type_distribution": distribution,
                "top_type": label,
                "source": metadata["source"],
                "training_weight": training_weight,
                "format_candidates": format_candidates,
                "rule_verified": False,
            }
        ],
    }


def validate_seed_records(records: list[dict[str, Any]], training_labels: set[str]) -> list[str]:
    errors: list[str] = []
    for record in records:
        text = record.get("text", "")
        spans = record.get("spans", [])
        if record.get("metadata", {}).get("subtype") == "doc_level" and spans != []:
            errors.append(f"{record.get('id')}: document-level negative must have empty spans")
        for span in spans:
            if text[span["start"] : span["end"]] != span.get("value"):
                errors.append(f"{record.get('id')}: offset mismatch")
            labels = set(span.get("type_distribution", {})) | {span.get("top_type")} | set(span.get("format_candidates", []))
            outside = sorted(label for label in labels if label not in training_labels)
            if outside:
                errors.append(f"{record.get('id')}: labels outside training space {outside}")
            dist = span.get("type_distribution", {})
            if abs(sum(float(v) for v in dist.values()) - 1.0) > 0.02:
                errors.append(f"{record.get('id')}: distribution does not sum to 1")
            if record.get("metadata", {}).get("subtype") == "candidate_level":
                if "NON_PII" not in dist or float(dist["NON_PII"]) <= 0.5:
                    errors.append(f"{record.get('id')}: candidate-level negative must be NON_PII-dominant")
    return errors


def validate_prompt_records(prompts: list[dict[str, Any]], training_labels: set[str]) -> list[str]:
    errors: list[str] = []
    for prompt in prompts:
        outside = [label for label in prompt.get("candidate_labels", []) if label not in training_labels]
        if outside:
            errors.append(f"{prompt.get('id')}: candidate labels outside training space {outside}")
        for verdict in VERDICTS:
            if verdict not in prompt.get("prompt", ""):
                errors.append(f"{prompt.get('id')}: missing verdict {verdict}")
    return errors


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in rows) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--zero-examples-per-label", type=int, default=20)
    parser.add_argument("--prompt-sample-size", type=int, default=20)
    args = parser.parse_args(argv)
    plan = generate_stage2_artifacts(
        args.root,
        zero_examples_per_label=args.zero_examples_per_label,
        prompt_sample_size=args.prompt_sample_size,
    )
    print(json.dumps(plan, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
