from __future__ import annotations

import argparse
import asyncio
import json
import time
from collections import Counter
from pathlib import Path
from typing import Any, Awaitable, Callable, Protocol

from pii_prep.stage2_full_teacher import load_all_raw_rows, run_full_teacher_async
from pii_prep.stage2_teacher_dryrun import (
    build_error_report,
    build_json_only_prompt,
    build_report,
    convert_raw_outputs,
    extract_json_object,
    validate_converted_rows,
    write_json,
    write_jsonl,
)
from pii_prep.stage2_vllm_quality import analyze_quality


AsyncSender = Callable[[dict[str, Any], dict[str, Any], str], Awaitable[str]]


class LocalTeacherRunner(Protocol):
    def generate(self, prompt: str) -> str:
        ...


RunnerFactory = Callable[[str, int], LocalTeacherRunner]


HARD_NEGATIVE_CONTEXT_TYPE = "hard_negative_context"
DEFAULT_TEACHER_MODEL_PATH = "/home/admin/model/Qwen3.6-27B"


HARD_NEGATIVE_SCENARIOS: list[dict[str, Any]] = [
    {
        "id": "bank_name_not_account",
        "span_value": "Southern Mutual",
        "contexts": [
            'Bank name written as "Southern Mutual"; acct: 0088 1992 44.',
            'Refund form lists bank name "Southern Mutual" beside a separate account number field.',
        ],
        "candidate_labels": ["BANK_ACCOUNT_NUMBER", "BANK_ACCOUNT_INFORMATION", "NON_PII"],
        "reason": "institution name is not an account identifier by itself",
    },
    {
        "id": "internal_ip",
        "span_value": "192.168.1.1",
        "contexts": [
            "Router setup guide says open http://192.168.1.1 before configuring the lab network.",
            "Example internal gateway 192.168.1.1 appears in the public troubleshooting page.",
        ],
        "candidate_labels": ["IP_ADDRESS", "DEVICE_ID", "NON_PII"],
        "reason": "private-network documentation value",
    },
    {
        "id": "main_line_phone",
        "span_value": "+61 2 9351 2222",
        "contexts": [
            "Admissions office main line: +61 2 9351 2222.",
            "For public enquiries call reception on +61 2 9351 2222.",
        ],
        "candidate_labels": ["MOBILE", "HOME_PHONE", "WORK_PHONE", "NON_PII"],
        "reason": "public organisation contact number",
    },
    {
        "id": "placeholder_email",
        "span_value": "student@example.edu.au",
        "contexts": [
            "The user guide uses student@example.edu.au as a placeholder address.",
            "Sample CSV column shows student@example.edu.au for documentation only.",
        ],
        "candidate_labels": ["EMAIL_ADDRESS", "WORK_EMAIL", "USERNAME", "NON_PII"],
        "reason": "placeholder address in documentation",
    },
    {
        "id": "course_code_not_student_id",
        "span_value": "COMP5703",
        "contexts": [
            "Course code COMP5703 appears in the assessment timetable.",
            "Students enrolled in COMP5703 should read the public course outline.",
        ],
        "candidate_labels": ["STUDENT_ID", "UAC_ID", "USERNAME", "NON_PII"],
        "reason": "course code is not an individual identifier",
    },
    {
        "id": "order_number_not_bank",
        "span_value": "0088 1992 44",
        "contexts": [
            "Order reference 0088 1992 44 was generated by the warehouse system.",
            "Invoice number 0088 1992 44 appears in the public sample document.",
        ],
        "candidate_labels": ["BANK_ACCOUNT_NUMBER", "STUDENT_ID", "EMPLOYEE_NUMBER", "NON_PII"],
        "reason": "business reference number despite account-like format",
    },
    {
        "id": "sandbox_card",
        "span_value": "4111 1111 1111 1111",
        "contexts": [
            "Sandbox payment test token 4111 1111 1111 1111 is documented for developers.",
            "Use demo card 4111 1111 1111 1111 in the non-production tutorial.",
        ],
        "candidate_labels": ["PAYMENT_CARD_NUMBER", "HASHED_PAYMENT_CARD_NUMBER", "NON_PII"],
        "reason": "well-known test card value",
    },
    {
        "id": "asset_code_not_rego",
        "span_value": "ASSET-ABC123",
        "contexts": [
            "Asset tag ASSET-ABC123 was printed on the equipment inventory sheet.",
            "Demo build code ASSET-ABC123 appears in release notes.",
        ],
        "candidate_labels": ["VEHICLE_REGO", "NUMBER_PLATE", "DEVICE_ID", "NON_PII"],
        "reason": "asset/build code, not a vehicle registration",
    },
    {
        "id": "metadata_month_not_expiry",
        "span_value": "05/2029",
        "contexts": [
            "Report generated for period 05/2029 by the analytics job.",
            "Archive folder 05/2029 stores monthly public reports.",
        ],
        "candidate_labels": ["CREDIT_CARD_EXPIRY", "MEDICARE_EXPIRY", "PASSPORT_EXPIRY", "NON_PII"],
        "reason": "document period, not credential expiry",
    },
    {
        "id": "public_url_not_account",
        "span_value": "https://example.edu.au/students/forms",
        "contexts": [
            "Public handbook link: https://example.edu.au/students/forms.",
            "Template footer points to https://example.edu.au/students/forms for more information.",
        ],
        "candidate_labels": ["WEBSITE_HISTORY", "SOCIAL_MEDIA_ACCOUNT", "USERNAME", "NON_PII"],
        "reason": "public URL, not personal browsing history",
    },
]


def build_hard_negative_teacher_prompts(
    training_labels: set[str],
    *,
    examples_per_scenario: int = 2,
    self_consistency: int = 1,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    if "NON_PII" not in training_labels:
        raise ValueError("training label space must include NON_PII")
    if examples_per_scenario <= 0:
        raise ValueError("examples_per_scenario must be positive")
    if self_consistency <= 0:
        raise ValueError("self_consistency must be positive")

    prompts: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    base_index = 0
    for scenario in HARD_NEGATIVE_SCENARIOS:
        candidates = compatible_candidates(scenario["candidate_labels"], training_labels)
        if len(candidates) <= 1:
            skipped.append({"id": scenario["id"], "reason": "not enough labels in training space", "candidate_labels": candidates})
            continue
        contexts = scenario["contexts"]
        for example_index in range(examples_per_scenario):
            base_index += 1
            context = contexts[example_index % len(contexts)]
            base_id = f"STAGE2-HARDNEG-BASE-{base_index:04d}"
            for consistency_index in range(1, self_consistency + 1):
                prompt = {
                    "id": f"{base_id}-SC{consistency_index}",
                    "base_prompt_id": base_id,
                    "self_consistency_index": consistency_index,
                    "ambiguity_group": f"hard_negative_{scenario['id']}",
                    "context_type": HARD_NEGATIVE_CONTEXT_TYPE,
                    "pilot_category": "candidate_level_hard_negative",
                    "generation_bucket": "candidate_level_hard_negative",
                    "span_value": scenario["span_value"],
                    "context": context,
                    "candidate_labels": candidates,
                    "expected_top_type": "NON_PII",
                    "hard_negative_reason": scenario["reason"],
                    "teacher_model_path": DEFAULT_TEACHER_MODEL_PATH,
                    "teacher_call_status": "not_run",
                }
                prompt["prompt"] = build_json_only_prompt(prompt)
                prompts.append(prompt)

    report = {
        "teacher_prompt_count": len(prompts),
        "base_prompt_count": len({prompt["base_prompt_id"] for prompt in prompts}),
        "examples_per_scenario": examples_per_scenario,
        "self_consistency": self_consistency,
        "context_type": HARD_NEGATIVE_CONTEXT_TYPE,
        "scenario_count": len(HARD_NEGATIVE_SCENARIOS),
        "skipped_scenarios": skipped,
        "candidate_label_counts": dict(sorted(Counter(label for prompt in prompts for label in prompt["candidate_labels"]).items())),
        "scenario_prompt_counts": dict(sorted(Counter(prompt["ambiguity_group"] for prompt in prompts).items())),
        "merged_into_training_dataset": False,
        "student_training_started": False,
    }
    return prompts, report


def compatible_candidates(candidate_labels: list[str], training_labels: set[str]) -> list[str]:
    labels = [label for label in candidate_labels if label in training_labels and label != "NON_PII"]
    labels.append("NON_PII")
    return dedupe(labels)


def dedupe(labels: list[str]) -> list[str]:
    seen: set[str] = set()
    output: list[str] = []
    for label in labels:
        if label in seen:
            continue
        seen.add(label)
        output.append(label)
    return output


def generate_hard_negative_teacher_artifacts(
    root: Path | str = ".",
    *,
    examples_per_scenario: int = 2,
    self_consistency: int = 1,
) -> dict[str, Any]:
    root = Path(root)
    training_labels = set(json.loads((root / "pii_schema" / "training_label_space_80.json").read_text(encoding="utf-8")))
    prompts, report = build_hard_negative_teacher_prompts(
        training_labels,
        examples_per_scenario=examples_per_scenario,
        self_consistency=self_consistency,
    )
    generated_dir = root / "data" / "generated"
    reports_dir = root / "reports"
    generated_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)
    prompt_path = generated_dir / "stage2_hard_negative_teacher_prompts.jsonl"
    report_path = reports_dir / "stage2_hard_negative_teacher_plan.json"
    write_jsonl(prompt_path, prompts)
    write_json(report_path, report)
    return report


async def run_hard_negative_project_async(
    root: Path | str = ".",
    *,
    base_url: str = "http://localhost:8000/v1",
    model_name: str = DEFAULT_TEACHER_MODEL_PATH,
    concurrency: int = 16,
    max_tokens: int = 96,
    timeout_seconds: float = 240.0,
    max_retries: int = 1,
    examples_per_scenario: int = 2,
    self_consistency: int = 1,
    sender: AsyncSender | None = None,
) -> dict[str, Any]:
    root = Path(root)
    generated_dir = root / "data" / "generated"
    reports_dir = root / "reports"
    generated_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)
    training_labels = set(json.loads((root / "pii_schema" / "training_label_space_80.json").read_text(encoding="utf-8")))

    prompts, prompt_plan = build_hard_negative_teacher_prompts(
        training_labels,
        examples_per_scenario=examples_per_scenario,
        self_consistency=self_consistency,
    )
    prompt_path = generated_dir / "stage2_hard_negative_teacher_prompts.jsonl"
    raw_path = generated_dir / "stage2_hard_negative_teacher_raw.jsonl"
    converted_path = generated_dir / "stage2_hard_negative_teacher_converted.jsonl"
    progress_path = reports_dir / "stage2_hard_negative_teacher_progress.json"
    generation_report_path = reports_dir / "stage2_hard_negative_teacher_generation_report.json"
    errors_path = reports_dir / "stage2_hard_negative_teacher_errors.json"
    quality_path = reports_dir / "stage2_hard_negative_teacher_quality_report.json"
    warnings_path = reports_dir / "stage2_hard_negative_teacher_warning_examples.json"

    write_jsonl(prompt_path, prompts)
    new_rows, runtime = await run_full_teacher_async(
        prompts,
        raw_path=raw_path,
        progress_path=progress_path,
        base_url=base_url,
        model_name=model_name,
        concurrency=concurrency,
        max_tokens=max_tokens,
        timeout_seconds=timeout_seconds,
        max_retries=max_retries,
        progress_interval=100,
        sender=sender,
    )
    raw_rows = load_all_raw_rows(raw_path)
    converted_rows, conversion_errors = convert_raw_outputs(raw_rows, training_labels)
    validation = validate_converted_rows(converted_rows, training_labels)
    write_jsonl(converted_path, converted_rows)

    generation_report = build_report(
        raw_rows,
        converted_rows,
        conversion_errors,
        validation,
        backend="vllm_openai",
        wall_time_seconds=runtime["wall_time_seconds"],
    )
    generation_report.update(prompt_plan)
    generation_report.update(runtime)
    generation_report["new_rows_this_run"] = len(new_rows)
    generation_report["expected_teacher_calls"] = len(prompts)
    generation_report["teacher_calls_completed_total"] = len(raw_rows)
    generation_report["hard_negative_teacher_calls_completed"] = len(raw_rows) == len(prompts)
    generation_report["raw_output_written_incrementally"] = True
    generation_report["merged_into_training_dataset"] = False
    generation_report["student_training_started"] = False
    write_json(generation_report_path, generation_report)

    quality, warnings = analyze_quality(converted_rows)
    quality["conversion_validation"] = validation
    quality["inputs"] = {
        "converted_path": str(converted_path),
        "raw_path": str(raw_path),
        "raw_record_count": len(raw_rows),
    }
    quality["merged_into_training_dataset"] = False
    quality["student_training_started"] = False
    write_json(quality_path, quality)
    write_json(warnings_path, {"warning_examples": warnings, "warning_counts": quality["warning_counts"]})

    error_report = build_error_report(conversion_errors, validation, converted_rows)
    error_report["raw_status_counts"] = dict(sorted(Counter(str(row.get("status")) for row in raw_rows).items()))
    error_report["quality_warning_counts"] = quality["warning_counts"]
    error_report["merged_into_training_dataset"] = False
    error_report["student_training_started"] = False
    write_json(errors_path, error_report)
    return generation_report


def run_hard_negative_project(root: Path | str = ".", **kwargs: Any) -> dict[str, Any]:
    return asyncio.run(run_hard_negative_project_async(root, **kwargs))


class TransformersLocalTeacherRunner:
    def __init__(self, model_path: str, max_new_tokens: int):
        self.model_path = model_path
        self.max_new_tokens = max_new_tokens
        import torch
        from transformers import AutoModelForCausalLM, AutoModelForImageTextToText, AutoTokenizer

        self.torch = torch
        self.tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True, local_files_only=True, use_fast=True)
        if self.tokenizer.pad_token_id is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        dtype = torch.bfloat16 if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else torch.float16
        load_kwargs = {
            "trust_remote_code": True,
            "local_files_only": True,
            "dtype": dtype,
            "device_map": {"": 0} if torch.cuda.is_available() else None,
            "low_cpu_mem_usage": True,
        }
        try:
            self.model = AutoModelForImageTextToText.from_pretrained(model_path, **load_kwargs)
        except Exception:
            self.model = AutoModelForCausalLM.from_pretrained(model_path, **load_kwargs)
        self.model.eval()

    def generate(self, prompt: str) -> str:
        messages = [
            {"role": "system", "content": "You are a strict JSON generator for PII ambiguity verdicts. Return JSON only."},
            {"role": "user", "content": prompt},
        ]
        prompt_text = apply_chat_template_no_thinking(self.tokenizer, messages)
        inputs = self.tokenizer(prompt_text, return_tensors="pt")
        device = next(self.model.parameters()).device
        inputs = {key: value.to(device) for key, value in inputs.items()}
        with self.torch.no_grad():
            output_ids = self.model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=False,
                pad_token_id=self.tokenizer.pad_token_id,
                eos_token_id=self.tokenizer.eos_token_id,
            )
        new_tokens = output_ids[0, inputs["input_ids"].shape[-1] :]
        return self.tokenizer.decode(new_tokens, skip_special_tokens=True).strip()


def apply_chat_template_no_thinking(tokenizer: Any, messages: list[dict[str, str]]) -> str:
    try:
        return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True, enable_thinking=False)
    except TypeError:
        return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)


def run_local_transformers_outputs(
    prompts: list[dict[str, Any]],
    *,
    raw_path: Path,
    model_path: str,
    max_new_tokens: int,
    runner_factory: RunnerFactory | None = None,
) -> list[dict[str, Any]]:
    raw_path.parent.mkdir(parents=True, exist_ok=True)
    completed = completed_raw_ids(raw_path)
    pending = [prompt for prompt in prompts if prompt["id"] not in completed]
    runner = (runner_factory or TransformersLocalTeacherRunner)(model_path, max_new_tokens)
    rows: list[dict[str, Any]] = []
    with raw_path.open("a", encoding="utf-8") as handle:
        for prompt in pending:
            started = time.time()
            output_text = ""
            status = "error"
            error = None
            try:
                output_text = runner.generate(build_json_only_prompt(prompt))
                extract_json_object(output_text)
                status = "ok"
            except Exception as exc:
                error = repr(exc)
                status = "malformed_or_error"
            row = {
                "id": prompt["id"],
                "prompt": prompt,
                "output_text": output_text if status == "ok" else "",
                "status": status,
                "error": error,
                "elapsed_seconds": round(time.time() - started, 3),
                "teacher_model_path": model_path,
                "generation_settings": {
                    "backend": "local_transformers",
                    "model": model_path,
                    "max_new_tokens": max_new_tokens,
                    "do_sample": False,
                    "flash_linear_attention_available": flash_linear_attention_available(),
                },
                "backend": "local_transformers",
                "retry_count": 0,
            }
            rows.append(row)
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
            handle.flush()
    return rows


def completed_raw_ids(raw_path: Path) -> set[str]:
    if not raw_path.exists():
        return set()
    completed: set[str] = set()
    for line in raw_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if row.get("status") == "ok":
            completed.add(str(row.get("id")))
    return completed


def flash_linear_attention_available() -> bool:
    try:
        import fla  # noqa: F401

        return True
    except Exception:
        return False


def run_hard_negative_local_project(
    root: Path | str = ".",
    *,
    model_name: str = "/home/admin/model/Qwen3.6-27B",
    max_tokens: int = 96,
    examples_per_scenario: int = 2,
    self_consistency: int = 1,
    runner_factory: RunnerFactory | None = None,
) -> dict[str, Any]:
    root = Path(root)
    generated_dir = root / "data" / "generated"
    reports_dir = root / "reports"
    generated_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)
    training_labels = set(json.loads((root / "pii_schema" / "training_label_space_80.json").read_text(encoding="utf-8")))
    prompts, prompt_plan = build_hard_negative_teacher_prompts(
        training_labels,
        examples_per_scenario=examples_per_scenario,
        self_consistency=self_consistency,
    )
    prompt_path = generated_dir / "stage2_hard_negative_teacher_prompts.jsonl"
    raw_path = generated_dir / "stage2_hard_negative_teacher_raw.jsonl"
    converted_path = generated_dir / "stage2_hard_negative_teacher_converted.jsonl"
    generation_report_path = reports_dir / "stage2_hard_negative_teacher_generation_report.json"
    errors_path = reports_dir / "stage2_hard_negative_teacher_errors.json"
    quality_path = reports_dir / "stage2_hard_negative_teacher_quality_report.json"
    warnings_path = reports_dir / "stage2_hard_negative_teacher_warning_examples.json"
    write_jsonl(prompt_path, prompts)

    started = time.time()
    new_rows = run_local_transformers_outputs(
        prompts,
        raw_path=raw_path,
        model_path=model_name,
        max_new_tokens=max_tokens,
        runner_factory=runner_factory,
    )
    raw_rows = load_all_raw_rows(raw_path)
    converted_rows, conversion_errors = convert_raw_outputs(raw_rows, training_labels)
    validation = validate_converted_rows(converted_rows, training_labels)
    write_jsonl(converted_path, converted_rows)

    generation_report = build_report(
        raw_rows,
        converted_rows,
        conversion_errors,
        validation,
        backend="local_transformers",
        wall_time_seconds=round(time.time() - started, 3),
    )
    generation_report.update(prompt_plan)
    generation_report["new_rows_this_run"] = len(new_rows)
    generation_report["expected_teacher_calls"] = len(prompts)
    generation_report["teacher_calls_completed_total"] = len(raw_rows)
    generation_report["hard_negative_teacher_calls_completed"] = len(raw_rows) == len(prompts)
    generation_report["flash_linear_attention_available"] = flash_linear_attention_available()
    generation_report["merged_into_training_dataset"] = False
    generation_report["student_training_started"] = False
    write_json(generation_report_path, generation_report)

    quality, warnings = analyze_quality(converted_rows)
    quality["conversion_validation"] = validation
    quality["inputs"] = {
        "converted_path": str(converted_path),
        "raw_path": str(raw_path),
        "raw_record_count": len(raw_rows),
    }
    quality["merged_into_training_dataset"] = False
    quality["student_training_started"] = False
    write_json(quality_path, quality)
    write_json(warnings_path, {"warning_examples": warnings, "warning_counts": quality["warning_counts"]})

    error_report = build_error_report(conversion_errors, validation, converted_rows)
    error_report["raw_status_counts"] = dict(sorted(Counter(str(row.get("status")) for row in raw_rows).items()))
    error_report["quality_warning_counts"] = quality["warning_counts"]
    error_report["merged_into_training_dataset"] = False
    error_report["student_training_started"] = False
    write_json(errors_path, error_report)
    return generation_report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--examples-per-scenario", type=int, default=2)
    parser.add_argument("--self-consistency", type=int, default=1)
    parser.add_argument("--run-teacher", action="store_true")
    parser.add_argument("--backend", choices=["vllm", "local"], default="vllm")
    parser.add_argument("--base-url", default="http://localhost:8000/v1")
    parser.add_argument("--model", default=DEFAULT_TEACHER_MODEL_PATH)
    parser.add_argument("--concurrency", type=int, default=16)
    parser.add_argument("--max-tokens", type=int, default=96)
    parser.add_argument("--timeout-seconds", type=float, default=240.0)
    parser.add_argument("--max-retries", type=int, default=1)
    args = parser.parse_args(argv)
    if args.run_teacher:
        if args.backend == "local":
            report = run_hard_negative_local_project(
                args.root,
                model_name=args.model,
                max_tokens=args.max_tokens,
                examples_per_scenario=args.examples_per_scenario,
                self_consistency=args.self_consistency,
            )
        else:
            report = run_hard_negative_project(
                args.root,
                base_url=args.base_url,
                model_name=args.model,
                concurrency=args.concurrency,
                max_tokens=args.max_tokens,
                timeout_seconds=args.timeout_seconds,
                max_retries=args.max_retries,
                examples_per_scenario=args.examples_per_scenario,
                self_consistency=args.self_consistency,
            )
    else:
        report = generate_hard_negative_teacher_artifacts(
            args.root,
            examples_per_scenario=args.examples_per_scenario,
            self_consistency=args.self_consistency,
        )
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
