import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from pii_prep.stage2_teacher_dryrun import (
    build_json_only_prompt,
    convert_raw_output,
    extract_json_object,
    run_vllm_openai_outputs,
    verdicts_to_distribution,
    validate_converted_rows,
)


class Stage2TeacherDryRunTests(unittest.TestCase):
    def test_extract_json_object_handles_wrapped_model_text(self):
        text = 'Sure.\n{"verdicts":{"NON_PII":"neutral"}}\nDone.'
        self.assertEqual(extract_json_object(text), {"verdicts": {"NON_PII": "neutral"}})

    def test_verdicts_to_distribution_uses_v32_multipliers(self):
        dist = verdicts_to_distribution(
            {
                "BANK_ACCOUNT_NUMBER": "strong_for",
                "STUDENT_ID": "weak_for",
                "NON_PII": "weak_against",
            },
            ["BANK_ACCOUNT_NUMBER", "STUDENT_ID", "NON_PII"],
        )
        self.assertAlmostEqual(sum(dist.values()), 1.0, places=6)
        self.assertGreater(dist["BANK_ACCOUNT_NUMBER"], dist["STUDENT_ID"])
        self.assertGreater(dist["STUDENT_ID"], dist["NON_PII"])

    def test_bare_span_calibration_downgrades_non_unique_strong_for(self):
        dist = verdicts_to_distribution(
            {"DATE_OF_BIRTH": "strong_for", "PASSPORT_EXPIRY": "weak_for", "NON_PII": "weak_against"},
            ["DATE_OF_BIRTH", "PASSPORT_EXPIRY", "NON_PII"],
            {"context_type": "bare_span", "span_value": "04/05/1998"},
        )

        self.assertLessEqual(dist["DATE_OF_BIRTH"], 0.60)
        self.assertAlmostEqual(sum(dist.values()), 1.0, places=6)

    def test_reverse_negative_calibration_promotes_non_pii_for_non_pii_context(self):
        dist = verdicts_to_distribution(
            {"PAYMENT_CARD_NUMBER": "strong_for", "NON_PII": "weak_against"},
            ["PAYMENT_CARD_NUMBER", "NON_PII"],
            {"context_type": "reverse_negative_context", "context": "Test token 4111111111111111 was generated by the sandbox."},
        )

        self.assertGreater(dist["NON_PII"], dist["PAYMENT_CARD_NUMBER"])

    def test_hard_negative_calibration_promotes_non_pii_for_public_context(self):
        dist = verdicts_to_distribution(
            {"BANK_ACCOUNT_NUMBER": "strong_for", "BANK_ACCOUNT_INFORMATION": "weak_for", "NON_PII": "weak_against"},
            ["BANK_ACCOUNT_NUMBER", "BANK_ACCOUNT_INFORMATION", "NON_PII"],
            {
                "context_type": "hard_negative_context",
                "span_value": "Southern Mutual",
                "context": 'Bank name written as "Southern Mutual", account number is stored elsewhere.',
            },
        )

        self.assertEqual(max(dist, key=dist.get), "NON_PII")
        self.assertGreater(dist["NON_PII"], dist["BANK_ACCOUNT_NUMBER"])

    def test_json_prompt_includes_context_specific_rules(self):
        prompt = build_json_only_prompt(
            {
                "candidate_labels": ["DATE_OF_BIRTH", "PASSPORT_EXPIRY", "NON_PII"],
                "context_type": "bare_span",
                "span_value": "04/05/1998",
                "context": "04/05/1998",
            }
        )

        self.assertIn("Date-like bare spans must remain ambiguous", prompt)
        self.assertIn("reverse_negative", prompt)

    def test_convert_raw_output_and_validation(self):
        prompt = {
            "id": "p1",
            "candidate_labels": ["BANK_ACCOUNT_NUMBER", "STUDENT_ID", "NON_PII"],
            "span_value": "123456",
            "context": "BSB 123456",
        }
        raw = {
            "id": "p1",
            "prompt": prompt,
            "output_text": json.dumps(
                {
                    "verdicts": {
                        "BANK_ACCOUNT_NUMBER": "strong_for",
                        "STUDENT_ID": "weak_against",
                        "NON_PII": "weak_against",
                    }
                }
            ),
            "status": "ok",
        }
        converted, errors = convert_raw_output(raw, {"BANK_ACCOUNT_NUMBER", "STUDENT_ID", "NON_PII"})

        self.assertEqual(errors, [])
        self.assertEqual(converted["top_type"], "BANK_ACCOUNT_NUMBER")
        self.assertAlmostEqual(sum(converted["type_distribution"].values()), 1.0, places=6)

        validation = validate_converted_rows([converted], {"BANK_ACCOUNT_NUMBER", "STUDENT_ID", "NON_PII"})
        self.assertEqual(validation["validation_error_count"], 0)
        self.assertEqual(validation["labels_outside_training_space"], {})

    def test_unexpected_labels_are_reported(self):
        prompt = {"id": "p2", "candidate_labels": ["NON_PII"], "span_value": "abc", "context": "abc"}
        raw = {
            "id": "p2",
            "prompt": prompt,
            "output_text": '{"verdicts":{"OUTSIDE":"strong_for","NON_PII":"neutral"}}',
            "status": "ok",
        }

        converted, errors = convert_raw_output(raw, {"NON_PII"})

        self.assertIsNone(converted)
        self.assertTrue(any("unexpected verdict label" in error for error in errors))

    def test_vllm_openai_backend_posts_chat_completion_request(self):
        prompt = {
            "id": "p3",
            "candidate_labels": ["PERSON", "NON_PII"],
            "span_value": "Mia",
            "context": "First name: Mia",
        }

        class FakeResponse:
            def __enter__(self):
                return self

            def __exit__(self, exc_type, exc, tb):
                return False

            def read(self):
                return json.dumps(
                    {
                        "choices": [
                            {
                                "message": {
                                    "content": json.dumps(
                                        {
                                            "verdicts": {
                                                "PERSON": "weak_for",
                                                "NON_PII": "weak_against",
                                            }
                                        }
                                    )
                                }
                            }
                        ]
                    }
                ).encode("utf-8")

        captured = {}

        def fake_urlopen(request, timeout):
            captured["url"] = request.full_url
            captured["payload"] = json.loads(request.data.decode("utf-8"))
            captured["timeout"] = timeout
            return FakeResponse()

        with patch("urllib.request.urlopen", fake_urlopen):
            rows = run_vllm_openai_outputs(
                [prompt],
                base_url="http://localhost:8000/v1",
                model_name="/model/path",
                max_tokens=64,
                raw_output_path=None,
            )

        self.assertEqual(captured["url"], "http://localhost:8000/v1/chat/completions")
        self.assertFalse(captured["payload"]["temperature"])
        self.assertEqual(captured["payload"]["max_tokens"], 64)
        self.assertEqual(rows[0]["status"], "ok")
        self.assertIn('"PERSON": "weak_for"', rows[0]["output_text"])


if __name__ == "__main__":
    unittest.main()
